services:
#    user.example:
#        class: MyApp\UserBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    AfterLoginRedirection:
        class: MyApp\UserBundle\Redirection\AfterLoginRedirection
        arguments: ["@router"]

